apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-dmos-config
  namespace: monitoring
data:
  config.yml: |
    global:
      resolve_timeout: 5m
    
    route:
      receiver: dmos-webhook
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 5m
      group_by: ['alertname', 'service']
    
    receivers:
      - name: dmos-webhook
        webhook_configs:
          - url: 'http://192.168.5.12:8081/webhook/alert'  # IL TUO PC IP VPN
            send_resolved: true
            http_config:
              follow_redirects: true